default_stages: [commit, merge-commit, push, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [
            wip,
            build,
            chore,
            ci,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: eslint-quote-me-frontend
        files: '^Exercises/quote-me/frontend/.*$'
        name: eslint-quote-me
        entry: bash -c "cd Exercises/quote-me/frontend; npx eslint --fix ."
        language: node
      - id: test-quote-me-frontend
        files: '^Exercises/quote-me/frontend/.*$'
        name: test-quote-me
        entry: bash -c "cd Exercises/quote-me/frontend; npm test"
        language: node

      - id: eslint-grocery-store
        files: '^Exercises/grocery-store/.*$'
        name: eslint-grocery-store
        entry: bash -c "cd ./Exercises/grocery-store; npx eslint --fix ."
        language: node

      - id: eslint-navbar
        files: '^Exercises/navbar/.*$'
        name: eslint-navbar
        entry: bash -c "cd ./Exercises/navbar; npx eslint --fix ."
        language: node
