default_stages: [commit, merge-commit, push, manual, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  - repo: local
    hooks:
      - id: eslint-quote-me
        name: eslint-quote-me
        entry: bash -c "npx eslint --fix Exercises/quote-me"
        language: node
