name: pre-commit

on: [pull_request, push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: install quote-me
        working-directory: ./Exercises/quote-me
        run: npm install
      - uses: pre-commit/action@v3.0.0
