name: pre-commit

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install navbar
        working-directory: ./Exercises/navbar
        run: npm install
      - name: install grocery-store
        working-directory: ./Exercises/grocery-store
        run: npm install
      - name: install quote-me
        working-directory: ./Exercises/quote-me
        run: npm install
      - uses: pre-commit/action@v3.0.0
